import path from "path";
import { fileURLToPath } from 'url';
import { dirname } from 'path';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
export const MONGO_URI = "mongodb+srv://rickyandrianaivo:2tkMQr6UkB4vexKT@ids.ll4k7bh.mongodb.net/etokisana";
export const JWT_SECRET = 'e-tokisana';
export const EMAIL_HOST = 'commercegestion.com';
export const EMAIL_USERNAME = 'contact@commercegestion.com';
export const EMAIL_PASSWORD = 'Rzh398aNVtFZUu4';
export const FROM_EMAIL = 'contact@commercegestion.com';
export const EMAIL_PORT = 465;
export const BCRYPT_SALT = 10;
export const CLIENT_URL = 'https://www.commercegestion.com';
export const NODE_ENV = 'DEV';
export const MAILTRAP_HOST = 'sandbox.smtp.mailtrap.io';
export const MAILTRAP_PORT = 2525;
export const MAILTRAP_USER = '2a6a049ea742dd';
export const MAILTRAP_PASS = '1b8d17f7b2651a';
export const PORT_DEV = 3000;
export const LIMIT = '50mb';
export const EMAIL_TEMPLATE_PATH = path.join(__dirname, '../../Utils/Emails/Template');
//# sourceMappingURL=constant.js.map